# Generated by Django 4.1.5 on 2023-02-12 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='publishing_time',
            new_name='registration_time',
        ),
        migrations.AddField(
            model_name='boardroom',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Администратор'),
        ),
        migrations.AddField(
            model_name='boardroom',
            name='creation_time',
            field=models.DateTimeField(null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='boardroom',
            name='type',
            field=models.TextField(choices=[('Публичная', 'Присоединиться может кто угодно'), ('Приватная', 'Для присоединения необходимо разрешение администратора')], default='Публичная', verbose_name='Тип'),
        ),
    ]
