# Generated by Django 4.1.5 on 2023-02-12 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_publishing_time_customuser_registration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardroom',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='boardroom',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
