# Generated by Django 4.1.5 on 2023-02-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_boardroom_admin_alter_boardroom_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardroom',
            name='main_position',
            field=models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR', max_length=100, verbose_name='Позиция'),
        ),
    ]
