# Generated by Django 4.1.5 on 2023-02-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_boardroom_main_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardroom',
            name='status',
            field=models.TextField(choices=[('Публичная', 'Присоединиться может кто угодно'), ('Приватная', 'Для присоединения необходимо разрешение администратора')], default='Онлайн', verbose_name='Тип'),
        ),
    ]
