# Generated by Django 4.1.5 on 2023-02-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_boardroom_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardroom',
            name='status',
            field=models.TextField(choices=[('Онлайн', 'Один или несколько администраторов в сети'), ('Офлайн', 'В сети нет ни одного администратора')], default='Онлайн', verbose_name='Статус'),
        ),
    ]
